#conce properties
#Sat May 30 15:49:23 BRT 2026
FRAME_CHARVS_KNOW_COMP_SPLITTER_CLASS_GROUP=55
FRAME_CHARVS_KNOW_HEIGHT=313
FRAME_CHARVS_KNOW_LEFT=768
FRAME_CHARVS_KNOW_ON_TOP=false
FRAME_CHARVS_KNOW_TOP=408
FRAME_CHARVS_KNOW_WIDTH=459
